import React, { useMemo, useState } from 'react';
import { AppConfig, ExternalTool, OrgEntity } from '../types';

const emptyTool = (): ExternalTool => ({ id: `tool-${Date.now()}`, name: '', description: '', logoUrl: '', url: '', audienceCompanies: ['*'], sortOrder: 1, enabled: true });
const ExternalToolsAdmin: React.FC<{ appConfig: AppConfig; orgEntities: OrgEntity[]; onUpdateConfig: (config: AppConfig) => Promise<void> | void }> = ({ appConfig, orgEntities, onUpdateConfig }) => {
  const [draft, setDraft] = useState<ExternalTool>(emptyTool());
  const companies = useMemo(() => orgEntities.filter(e => e.active && e.entityType !== 'shareholder').sort((a,b)=>a.sortOrder-b.sortOrder), [orgEntities]);
  const tools = [...(appConfig.externalTools || [])].sort((a,b)=>a.sortOrder-b.sortOrder);
  const saveAll = (next: ExternalTool[]) => onUpdateConfig({ ...appConfig, externalTools: next });
  const add = async () => { if (!draft.name.trim() || !draft.url.trim()) return alert('Nom et URL sont obligatoires.'); const url = /^https?:\/\//i.test(draft.url) ? draft.url : `https://${draft.url}`; await saveAll([...tools, {...draft, name:draft.name.trim(), url, sortOrder: tools.length+1}]); setDraft(emptyTool()); };
  const patch = (id:string, changes:Partial<ExternalTool>) => saveAll(tools.map(t=>t.id===id?{...t,...changes}:t));
  const remove = (id:string) => window.confirm('Supprimer cet outil ?') && saveAll(tools.filter(t=>t.id!==id).map((t,i)=>({...t,sortOrder:i+1})));
  const toggleAudience = (tool:ExternalTool, company:string) => { const current=tool.audienceCompanies||['*']; const next=company==='*' ? ['*'] : current.includes('*') ? [company] : current.includes(company) ? current.filter(x=>x!==company) : [...current,company]; patch(tool.id,{audienceCompanies:next.length?next:['*']}); };
  return <div className="max-w-4xl space-y-7 text-left"><div><h2 className="text-2xl font-black text-slate-800">Mes outils</h2><p className="text-slate-500 mt-1">Applications externes visibles par les salariés selon leur entreprise.</p></div>
    <div className="bg-white border border-slate-200 rounded-[32px] p-6 space-y-4"><h3 className="font-black text-slate-800">Ajouter un outil</h3><div className="grid md:grid-cols-2 gap-3"><input className="bg-slate-50 border rounded-2xl px-4 py-3" placeholder="Nom" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><input className="bg-slate-50 border rounded-2xl px-4 py-3" placeholder="Description" value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value})}/><input className="bg-slate-50 border rounded-2xl px-4 py-3" placeholder="https://..." value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})}/><input className="bg-slate-50 border rounded-2xl px-4 py-3" placeholder="URL du logo (optionnel)" value={draft.logoUrl||''} onChange={e=>setDraft({...draft,logoUrl:e.target.value})}/></div><button onClick={add} className="px-5 py-3 rounded-2xl bg-purple-600 text-white font-black">+ Ajouter</button></div>
    <div className="space-y-4">{tools.map(tool=><div key={tool.id} className="bg-white border border-slate-200 rounded-[28px] p-6 space-y-4"><div className="flex flex-wrap items-center gap-3"><input className="font-black text-lg flex-1 min-w-48 border-b outline-none" value={tool.name} onChange={e=>patch(tool.id,{name:e.target.value})}/><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={tool.enabled} onChange={e=>patch(tool.id,{enabled:e.target.checked})}/> Actif</label><button onClick={()=>remove(tool.id)} className="text-red-600 font-bold text-sm">Supprimer</button></div><div className="grid md:grid-cols-2 gap-3"><input className="bg-slate-50 border rounded-xl px-3 py-2" value={tool.description||''} onChange={e=>patch(tool.id,{description:e.target.value})}/><input className="bg-slate-50 border rounded-xl px-3 py-2" value={tool.url} onChange={e=>patch(tool.id,{url:e.target.value})}/><input className="bg-slate-50 border rounded-xl px-3 py-2 md:col-span-2" placeholder="URL du logo" value={tool.logoUrl||''} onChange={e=>patch(tool.id,{logoUrl:e.target.value})}/></div><div><p className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-2">Visible par</p><div className="flex flex-wrap gap-2"><button onClick={()=>toggleAudience(tool,'*')} className={`px-3 py-2 rounded-xl text-xs font-bold ${tool.audienceCompanies.includes('*')?'bg-green-700 text-white':'bg-slate-100 text-slate-600'}`}>Toutes les entreprises</button>{companies.map(c=><button key={c.id} onClick={()=>toggleAudience(tool,c.name)} className={`px-3 py-2 rounded-xl text-xs font-bold ${tool.audienceCompanies.includes(c.name)?'bg-green-700 text-white':'bg-slate-100 text-slate-600'}`}>{c.name}</button>)}</div></div></div>)}</div>
  </div>;
};
export default ExternalToolsAdmin;
