import React, { useEffect, useState } from 'react';
import { OrgEntity, ResourceItem, User } from '../types';
import { supabase } from '../supabaseClient';
import { uploadMediaToStorage } from '../storageUtils';
import AudienceSelector from './AudienceSelector';
import { AUDIENCE_ALL } from '../audience';

const empty = { title:'', summary:'', content:'', category:'Général', mediaType:'text', resourceUrl:'', thumbnailUrl:'', audience:AUDIENCE_ALL, published:true };
const ResourcesAdmin:React.FC<{currentUser:User; entities:OrgEntity[]}> = ({currentUser, entities}) => {
 const [items,setItems]=useState<ResourceItem[]>([]); const [form,setForm]=useState(empty); const [saving,setSaving]=useState(false); const [progress,setProgress]=useState<number|null>(null);
 const load=async()=>{ if(!supabase)return; const {data}=await supabase.from('learning_resources').select('*').order('created_at',{ascending:false}); if(data)setItems(data.map((r:any)=>({id:r.id,title:r.title,summary:r.summary||'',content:r.content||'',category:r.category||'Général',mediaType:r.media_type||'text',resourceUrl:r.resource_url||'',thumbnailUrl:r.thumbnail_url||'',audienceCompanies:r.audience_companies||['ALL'],published:r.published!==false,sortOrder:r.sort_order||0,createdAt:r.created_at})));};
 useEffect(()=>{void load();},[]);
 const upload=async(file:File)=>{setProgress(0);try{const url=await uploadMediaToStorage(file,'resources',p=>setProgress(p));setForm(f=>({...f,resourceUrl:url,mediaType:file.type.startsWith('video/')?'video':file.type.startsWith('image/')?'image':'document'}));}catch(e:any){alert(e?.message||'Upload impossible');}finally{setProgress(null);}};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase||!form.title.trim())return;setSaving(true);const {error}=await supabase.from('learning_resources').insert({title:form.title.trim(),summary:form.summary.trim(),content:form.content.trim(),category:form.category.trim()||'Général',media_type:form.mediaType,resource_url:form.resourceUrl.trim()||null,thumbnail_url:form.thumbnailUrl.trim()||null,audience_companies:[form.audience],published:form.published,created_by:currentUser.id});setSaving(false);if(error){alert(error.message);return;}setForm(empty);void load();};
 return <div className="space-y-6 text-left"><div><h2 className="text-2xl font-black text-slate-800">Gestion des Ressources</h2><p className="text-sm text-slate-500 mt-1">Publiez les contenus pédagogiques de Ressources & Jeux. L'espace Jeux existant reste indépendant.</p></div>
 <form onSubmit={submit} className="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm grid grid-cols-1 md:grid-cols-2 gap-4">
  <div><label className="text-xs font-bold text-slate-500 uppercase">Titre</label><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="mt-2 w-full px-4 py-3 bg-slate-50 border rounded-xl" /></div>
  <div><label className="text-xs font-bold text-slate-500 uppercase">Thème</label><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Ex. Variétés, Métiers, Sécurité…" className="mt-2 w-full px-4 py-3 bg-slate-50 border rounded-xl" /></div>
  <div className="md:col-span-2"><label className="text-xs font-bold text-slate-500 uppercase">Résumé</label><input value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})} className="mt-2 w-full px-4 py-3 bg-slate-50 border rounded-xl" /></div>
  <div className="md:col-span-2"><label className="text-xs font-bold text-slate-500 uppercase">Contenu / informations</label><textarea rows={5} value={form.content} onChange={e=>setForm({...form,content:e.target.value})} className="mt-2 w-full px-4 py-3 bg-slate-50 border rounded-xl" /></div>
  <div><label className="text-xs font-bold text-slate-500 uppercase">Type</label><select value={form.mediaType} onChange={e=>setForm({...form,mediaType:e.target.value})} className="mt-2 w-full px-4 py-3 bg-slate-50 border rounded-xl"><option value="text">À lire</option><option value="document">Document</option><option value="video">Vidéo</option><option value="image">Image</option><option value="link">Lien</option></select></div>
  <div><label className="text-xs font-bold text-slate-500 uppercase">Lien / fichier</label><div className="mt-2 flex gap-2"><input value={form.resourceUrl} onChange={e=>setForm({...form,resourceUrl:e.target.value})} placeholder="URL ou fichier chargé" className="min-w-0 flex-1 px-4 py-3 bg-slate-50 border rounded-xl"/><label className="px-4 py-3 rounded-xl bg-slate-800 text-white font-bold cursor-pointer">Charger<input type="file" className="hidden" onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0])}/></label></div>{progress!==null&&<div className="mt-2 text-xs font-bold text-green-700">Téléversement : {progress}%</div>}</div>
  <div><label className="text-xs font-bold text-slate-500 uppercase">Image de couverture (URL)</label><input value={form.thumbnailUrl} onChange={e=>setForm({...form,thumbnailUrl:e.target.value})} className="mt-2 w-full px-4 py-3 bg-slate-50 border rounded-xl" /></div>
  <AudienceSelector currentUser={currentUser} entities={entities} value={form.audience} onChange={v=>setForm({...form,audience:v})}/>
  <label className="flex items-center gap-2 font-bold text-slate-700"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Publier immédiatement</label>
  <div className="md:col-span-2 flex justify-end"><button disabled={saving||progress!==null} className="px-7 py-3 bg-green-700 text-white rounded-xl font-black disabled:opacity-50">{saving?'Publication…':'Publier la ressource'}</button></div>
 </form>
 <div className="grid grid-cols-1 md:grid-cols-2 gap-4">{items.map(r=><div key={r.id} className="bg-white border rounded-2xl p-5 flex justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-widest text-green-700">{r.category} · {r.published?'Publié':'Brouillon'}</div><h3 className="font-black text-slate-800 mt-1">{r.title}</h3><p className="text-xs text-slate-400 mt-1">{r.audienceCompanies?.includes('ALL')?'Commun à tous':r.audienceCompanies?.join(', ')}</p></div><div className="flex flex-col gap-2"><button onClick={async()=>{await supabase?.from('learning_resources').update({published:!r.published}).eq('id',r.id);void load();}} className="text-xs font-bold text-indigo-600">{r.published?'Dépublier':'Publier'}</button><button onClick={async()=>{if(confirm('Supprimer cette ressource ?')){await supabase?.from('learning_resources').delete().eq('id',r.id);void load();}}} className="text-xs font-bold text-red-500">Supprimer</button></div></div>)}</div>
 </div>;
};
export default ResourcesAdmin;
